### ISSUE TITLE
RustBridge event in RustFest Barcelona (9-10 November)

### ISSUE THREAD

**Issue by jrvidal** [rustbridge/organizing#2]
https://barcelona.rustfest.eu/

* Coaches: @jrvidal
* Venue: [UPC - Universitat Politècnica de Catalunya](https://www.upc.edu/en)
* Date: 9-10 November (two days!)

**Comment by Dylan-DPC-zz** [comment]
@badboy sure. the only people on this thread volunteering (besides @jrvidal ) are @fmoko and me so I guess it's just me who needs the ticket :D

**Comment by manyinsects** [comment]
Postmortem: https://hackmd.io/@mokou/BJVk9irjS
